/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.tw.cn.cap.gtb.todo;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.util.ArrayList;
import java.util.List;

public class App {


    public static void main(String[] args) {
        throw new UnsupportedOperationException();
    }

    public List<String> run() {
        try {
            List<String> result = new ArrayList<>();
            result.add("# To be done");
            List<String> lines = Files.readAllLines(Constants.TASK_PATH, StandardCharsets.UTF_8);
            result.addAll(lines);
            return result;
        } catch (IOException e) {
            throw new AppCannotReadFileException(e);
        }
    }
}
